name: 📚 Documentation
description: Report documentation issues or suggest improvements
title: "[Docs]: "
labels: ["type: documentation", "triage: new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which documentation needs improvement?
      options:
        - README.md
        - CONTRIBUTING.md
        - FAQ.md
        - ROADMAP.md
        - CHANGELOG.md
        - Code comments / rustdoc
        - Docker setup guides (.env examples)
        - GitHub wiki
        - Other (please specify)
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: What's the issue?
      description: What's unclear, incorrect, outdated, or missing?
      placeholder: |
        The documentation says... but it should say...
        This section is confusing because...
        There's no documentation for...
    validations:
      required: true
      
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this be fixed or improved? (optional but helpful)
      placeholder: |
        Add a section explaining...
        Change the wording to...
        Include an example of...
        
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documentation? (URL, file path, or section name)
      placeholder: "e.g., README.md line 42, or https://github.com/..."
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information or examples
