name: 🔧 Enhancement
description: Suggest an improvement to existing functionality
title: "[Enhancement]: "
labels: ["type: enhancement", "triage: new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement!
        
        **Before submitting:** Please search [existing issues](https://github.com/Jagalite/superseedr/issues) to see if this has already been proposed.
        
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works
      placeholder: |
        Currently, when I...
        The feature does...
    validations:
      required: true
      
  - type: textarea
    id: proposed
    attributes:
      label: Proposed Improvement
      description: How could this be improved?
      placeholder: |
        Instead, it should...
        A better approach would be...
        This could be enhanced by...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Which component does this affect?
      description: What part of superseedr would this improve?
      options:
        - TUI/Interface
        - BitTorrent Protocol
        - Docker/VPN Integration
        - Networking/Port Management
        - Configuration/Settings
        - Performance/Efficiency
        - Documentation
        - Testing/CI-CD
        - Other (please specify below)
    validations:
      required: true
      
  - type: textarea
    id: benefit
    attributes:
      label: Benefits
      description: Why would this improvement be valuable?
      placeholder: |
        This would help users...
        The benefit would be...
        This solves the problem of...
    validations:
      required: true
      
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this change existing behavior?
      options:
        - label: This would be a breaking change
        - label: This affects private tracker builds
        
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots
      placeholder: Add any other relevant information here
