name: ✨ Feature Request
description: Suggest a new feature or capability
title: "[Feature]: "
labels: ["type: feature", "triage: new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 
        
        **Before submitting:** Please search [existing issues](https://github.com/Jagalite/superseedr/issues) and [discussions](https://github.com/Jagalite/superseedr/discussions) to see if this has already been proposed.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem or user need does this address?
      placeholder: |
        I'm frustrated when...
        Users need to be able to...
        Currently there's no way to...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        The feature would work like this...
        Users would interact with it by...
        It would appear in the TUI as...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions or Workarounds
      description: Have you considered any alternative solutions? Are there current workarounds?
      placeholder: |
        Alternative approach: ...
        Current workaround: ...
        
  - type: dropdown
    id: component
    attributes:
      label: Which component does this affect?
      description: Where would this feature live?
      options:
        - TUI/Interface
        - BitTorrent Protocol
        - Docker/VPN Integration
        - Networking/Port Management
        - Configuration/Settings
        - Performance/Efficiency
        - Documentation
        - Other (please specify below)
    validations:
      required: true
      
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require changes to existing behavior or configuration?
      options:
        - label: This would be a breaking change (requires user action, config migration, etc.)
        - label: This affects private tracker builds (DHT/PEX disabled)
          
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Any other context, examples, mockups, or links:
        - Similar features in other clients
        - Screenshots or mockups
        - Use case examples
      placeholder: Add any other context, screenshots, or examples here
